### ISSUE TITLE
Potential inconsistencies in Spotify header theming?

### ISSUE THREAD

**Issue by 676339784** [themix-project/oomoxify#2]
An album header (among other things, such as "Made For You" and "Recently Played tabs) might look like this with a sort of gray gradient, for example:

<img src="https://ptpb.pw/Pmx4.png">

On the other hand, headers for things like playlists and most other things are themed, which in my case is black:

<img src="https://ptpb.pw/28o8.png">

Is there a way the theme could be all-encompassing i.e. no inconsistencies as is right now. Or is that just my theme?

**Comment by 676339784** [comment]
This looked like the linear-gradient property in CSS (tried it out as well https://ptpb.pw/sRBl.png)

As such, I've updated lines that look like 

```
background: linear-gradient(to bottom, transparent, #000000);
```

to 

```
background: linear-gradient(to bottom, #000000, #000000);
```

to remove the gradient. However, no changes took place -- the album art header still has a gradient. Any suggestions on which .spa file(s) I should be editing or if that is even the correct method?

**Comment by actionless** [comment]
those CSS files are quite big and there lots of them so i was never reading them manually, i was just collecting some snippets from them with slightly modified version of the script (but with grep instead of sed) and applying some transformation and sorting of the results afterwards

**Comment by actionless** [comment]
ah, actually there is `--debug <search_keyword>` option of the script which is doing a simplified version of what i mentioned in the comment above

**Comment by actionless** [comment]
so as a starting point you could try something like: `oomoxify.sh --debug linear-gradient <some_other_params_like_spotify_path> | tr -d ' '  | sort -u `

**Comment by 676339784** [comment]
Nice, thanks for the pointers! Even after using the script with debug flag I still have a lot to sift through though and I'm not the most proficient with these tools -- could you help me take a look as to which .spa files I should be transforming? I used ```sed -i 's/linear-gradient(to bottom, transparent/linear-gradient(to bottom, #000000/g' *``` but it just made Spotify all black so I can't modify *everything* it seems like.

**Comment by actionless** [comment]
no, i'm too lazy to care about those gradients :-)

**Comment by actionless** [comment]
i think it's not reproducible anymore as spotify app changed their design several times
