### ISSUE TITLE
Silent Exit Code 1

### ISSUE THREAD

**Issue by JavaScythe** [themix-project/oomoxify#7]
oomoxify.sh (/opt/oomox/plugins/oomoxify/oomoxify) returns exit code 1.
the GUI version in themix also fails ("Something went wrong :(", with no error above it in the box)

The --debug flag produces an error: "./oomoxify.sh: line 72: 2: unbound variable"

Here is the command I am running
./oomoxify.sh -s /home/bingle/.local/share/spotify-launcher/install/usr/share/spotify/Apps /home/bingle/.config/oomox/colors/btheme

Spotify is installed at .local/spotify-launcher/install/usr/share/spotify (via arch package "spotify-launcher")
Spicetify has never been applied
I checked the logs from oomoxify in /tmp but it seems to just list style properties 

Please let me know if you need additional information

**Comment by actionless** [comment]
i can't just guess it without the logs
